-- ============================================================
-- Leave Details 2026 — auto-generated INSERT statements
-- ============================================================

CREATE TABLE IF NOT EXISTS leaves (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    employee_name TEXT    NOT NULL,
    leave_date    DATE    NOT NULL,
    leave_type    TEXT
);

CREATE TABLE IF NOT EXISTS public_holidays (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    holiday_date DATE    NOT NULL,
    description  TEXT,
    location     TEXT
);

-- Leave records
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Haresh Pole', '2026-01-07', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Haresh Pole', '2026-01-08', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Haresh Pole', '2026-01-09', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Haresh Pole', '2026-01-12', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Haresh Pole', '2026-01-13', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Pranay', '2026-01-23', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Edgar', '2026-01-19', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Edgar', '2026-01-20', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Edgar', '2026-01-21', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Edgar', '2026-01-22', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Edgar', '2026-01-23', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jenita', '2026-01-02', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jenita', '2026-01-15', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Fathima', '2026-01-07', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Fathima', '2026-01-21', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Kiran', '2026-01-14', 'Annual Earned leave, Comp-off');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Kiran', '2026-01-16', 'Annual Earned leave, Comp-off');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Tejaswini', '2026-01-13', 'Planned leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Tejaswini', '2026-01-14', 'Planned leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Tejaswini', '2026-01-16', 'Planned leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Ramya', '2026-01-15', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Ramya', '2026-01-20', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Ramya', '2026-01-21', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Ramya', '2026-01-22', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Bodj', '2026-01-05', 'Planned leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Bodj', '2026-01-19', 'Planned leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Bodj', '2026-01-26', 'Planned leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Sanjana', '2026-01-15', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Sanjana', '2026-01-16', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Paridhee', '2026-01-14', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Paridhee', '2026-01-29', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jed', '2026-01-16', 'Comp-Off');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jed', '2026-01-23', 'Comp-Off');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Madhavi', '2026-01-13', 'Comp-Off, restricted leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Madhavi', '2026-01-14', 'Comp-Off, restricted leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Pradeep', '2026-01-14', 'Comp off, Annual earned leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Pradeep', '2026-01-16', 'Comp off, Annual earned leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Sourabh Kumar', '2026-01-30', 'Comp Off');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-01-22', 'Planned Leave for marriage');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-01-23', 'Planned Leave for marriage');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-01-27', 'Planned Leave for marriage');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-01-28', 'Planned Leave for marriage');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-01-29', 'Planned Leave for marriage');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-01-30', 'Planned Leave for marriage');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Pranay', '2026-02-13', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Pranay', '2026-02-26', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Pranay', '2026-02-27', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Sourabh Kumar', '2026-02-02', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Sourabh Kumar', '2026-02-03', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Sourabh Kumar', '2026-02-04', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Sourabh Kumar', '2026-02-05', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Sourabh Kumar', '2026-02-06', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nancy', '2026-02-16', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nancy', '2026-02-17', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nancy', '2026-02-18', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nancy', '2026-02-20', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nancy', '2026-02-24', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Fathima', '2026-02-04', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Fathima', '2026-02-11', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Fathima', '2026-02-18', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jed', '2026-02-13', 'Comp-Off');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jed', '2026-02-20', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Abel', '2026-02-03', 'Comp-Off');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Tejaswini', '2026-02-26', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Praveen', '2026-02-12', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Praveen', '2026-02-13', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Praveen', '2026-02-20', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Abel', '2026-02-16', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jenita', '2026-02-13', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-02-02', 'Planned Leave for marriage');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-02-03', 'Planned Leave for marriage');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-02-04', 'Planned Leave for marriage');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-02-05', 'Planned Leave for marriage');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-02-06', 'Planned Leave for marriage');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-02-09', 'Planned Leave for marriage');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-02-10', 'Planned Leave for marriage');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-02-11', 'Planned Leave for marriage');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-02-12', 'Planned Leave for marriage');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-02-13', 'Planned Leave for marriage');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Pranay', '2026-03-20', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nancy', '2026-03-06', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Sanjana', '2026-03-10', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Sanjana', '2026-03-11', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Sanjana', '2026-03-12', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Sanjana', '2026-03-13', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jed', '2026-03-06', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jed', '2026-03-09', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Abel', '2026-03-05', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Abel', '2026-03-30', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Abel', '2026-03-31', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Tejaswini', '2026-03-16', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Tejaswini', '2026-03-20', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Tejaswini', '2026-03-26', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Praveen', '2026-03-23', 'Tentative');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Praveen', '2026-03-24', 'Tentative');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Bodj', '2026-03-02', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jenita', '2026-03-27', 'Tentative');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Madhavi', '2026-03-05', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Madhavi', '2026-03-25', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Gyan', '2026-03-30', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Gyan', '2026-03-31', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-03-18', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-03-20', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-03-23', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-03-26', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Bodj', '2026-04-06', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Bodj', '2026-04-24', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nancy', '2026-04-03', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nancy', '2026-04-14', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nancy', '2026-04-23', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Praveen', '2026-04-09', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Praveen', '2026-04-10', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Abel', '2026-04-01', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jenita', '2026-04-03', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Gyan', '2026-04-01', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Gyan', '2026-04-13', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Gyan', '2026-04-14', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Deeksha', '2026-04-06', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Deeksha', '2026-04-07', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Deeksha', '2026-04-08', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Deeksha', '2026-04-09', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Deeksha', '2026-04-10', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Paridhee', '2026-04-13', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Paridhee', '2026-04-27', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-04-29', 'Tentative, West Bengal Election');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Bodj', '2026-05-04', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Abel', '2026-05-21', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jenita', '2026-05-07', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jenita', '2026-05-08', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jenita', '2026-05-14', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Tejaswini', '2026-05-20', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Tejaswini', '2026-05-21', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Tejaswini', '2026-05-22', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Praveen', '2026-05-22', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Praveen', '2026-05-26', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Paridhee', '2026-05-06', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Paridhee', '2026-05-13', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Paridhee', '2026-05-27', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nancy', '2026-05-27', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nancy', '2026-05-28', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nancy', '2026-05-29', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-05-04', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-05-05', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-05-06', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Nadeem', '2026-05-07', 'Planned Leave');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jed', '2026-06-29', 'Planned Leaves(Tentative)');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jed', '2026-06-30', 'Planned Leaves(Tentative)');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Bodj', '2026-06-01', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Praveen', '2026-06-15', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Praveen', '2026-06-16', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Praveen', '2026-06-17', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Praveen', '2026-06-18', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Gyan', '2026-06-12', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Gyan', '2026-06-15', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jed', '2026-07-01', 'Planned Leaves(Tentative)');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jed', '2026-07-02', 'Planned Leaves(Tentative)');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jed', '2026-07-03', 'Planned Leaves(Tentative)');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Bodj', '2026-07-10', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Praveen', '2026-07-06', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Praveen', '2026-07-07', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Praveen', '2026-07-08', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Praveen', '2026-07-09', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Praveen', '2026-07-10', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jenita', '2026-08-11', NULL);
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jed', '2026-11-26', 'Planned Leaves');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jed', '2026-11-27', 'Planned Leaves');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jed', '2026-12-01', 'Planned Leaves');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jed', '2026-12-02', 'Planned Leaves');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jed', '2026-12-03', 'Planned Leaves');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jed', '2026-12-04', 'Planned Leaves');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jed', '2026-12-07', 'Planned Leaves');
INSERT INTO leaves (employee_name, leave_date, leave_type) VALUES ('Jed', '2026-12-08', 'PH Holiday');

-- Public holidays
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-02-17', NULL, NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-03-20', NULL, NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-04-02', NULL, NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-04-03', NULL, NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-04-04', NULL, NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-04-09', NULL, NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-04-19', NULL, 'DXC Bangalore');
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-04-14', NULL, 'DXC Chennai');
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-04-23', NULL, 'DXC Chennai');
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-05-01', NULL, NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-05-01', NULL, 'DXC India');
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-06-12', NULL, NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-08-21', NULL, NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-08-31', NULL, NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-11-01', NULL, NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-11-02', NULL, NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-11-30', NULL, NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-12-08', NULL, NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-12-24', NULL, NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-12-25', NULL, NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-12-30', NULL, NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-12-31', NULL, NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-12-21', '*Temp DXC Holiday Shutdown', NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-12-22', '*Temp DXC Holiday Shutdown', NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-12-23', '*Temp DXC Holiday Shutdown', NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-12-28', '*Temp DXC Holiday Shutdown', NULL);
INSERT INTO public_holidays (holiday_date, description, location) VALUES ('2026-12-29', '*Temp DXC Holiday Shutdown', NULL);